spring:
  application:
    name: fillin

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 기본 TTL: 1시간 (밀리초)

  profiles:
    active: local

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 2000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: FillinHikariPool

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        probes:
          enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION} # 예: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  file:
    #EC2 서버 내부 경로
    name: /home/ubuntu/fillin/logs/application.log
  logback:
    rollingpolicy:
      max-history: 7 # 로그 보관 기간 (서버 용량 관리용)
      max-file-size: 10MB # 파일당 최대 용량

server:
  tomcat:
    max-threads: 200              # 운영 인스턴스와 동일하게 유지
    accept-count: 100
    mbeanregistry:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_EXPIRE}    # 1시간
  refresh-token-validity: ${JWT_REFRESH_EXPIRE}  # 2주

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: http://localhost:8080/api/auth/kakao/callback    # 인가 코드

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: http://localhost:3000/oauth/google/callback

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  env: local

gemini:
  api-key: ${GEMINI_API_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="

gcv:
  api-key: ${GCV_API_KEY}

sentry:
  dsn: ${SENTRY_DSN}

  # 테스트 시에는 1.0으로 설정해서 모든 요청을 확인, 실제 운영 시에는 0.1(10%)
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483648
  logging:
    minimum-event-level: error # error 이상의 로그는 자동으로 Sentry 이슈로 생성
    minimum-breadcrumb-level: info # info 이상의 로그는 에러 발생 시 '이전 기록'으로 함께 전송